USE Livraria
GO

CREATE TABLE Clientes(
	Id INT PRIMARY KEY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	SexoAutor CHAR(1) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	Telefone VARCHAR(12),
	Endereco VARCHAR(100) NOT NULL
);